-- SQL Query to populate vendors in all categories
-- This will add 3 sample vendors to each of the 11 categories

-- First, let's disable RLS temporarily for easier insertion
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_media DISABLE ROW LEVEL SECURITY;

-- Insert Event Planners
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('dream-events-planner', 'Dream Events Planner', 'Priya Sharma', 'Event Planners', '+91 98765 43210', '+91 98765 43210', 'priya@dreamevents.com', 'Hyderabad, Telangana', 'Full-service wedding planning with attention to detail and personalized touch.', '5+ years', 4.8, 127, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Wedding Planning", "Corporate Events", "Birthday Parties"]', '["Full Planning", "Partial Planning", "Day Coordination"]', '[{"name": "Full Wedding Package", "price": "₹1,50,000", "features": ["Complete planning", "Vendor coordination", "Day management"]}]'),
('perfect-celebrations', 'Perfect Celebrations', 'Rajesh Kumar', 'Event Planners', '+91 98765 43211', '+91 98765 43211', 'rajesh@perfectcelebrations.com', 'Bangalore, Karnataka', 'Creative event solutions for memorable celebrations.', '3+ years', 4.6, 89, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Wedding Planning", "Anniversary", "Engagement"]', '["Event Design", "Vendor Management", "Timeline Creation"]', '[{"name": "Premium Package", "price": "₹2,00,000", "features": ["Complete planning", "Design consultation", "Vendor coordination"]}]'),
('royal-events', 'Royal Events', 'Sneha Patel', 'Event Planners', '+91 98765 43212', '+91 98765 43212', 'sneha@royalevents.com', 'Mumbai, Maharashtra', 'Luxury event planning with royal treatment.', '7+ years', 4.9, 203, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Luxury Weddings", "Destination Events", "Corporate Galas"]', '["Luxury Planning", "Destination Coordination", "VIP Services"]', '[{"name": "Royal Package", "price": "₹5,00,000", "features": ["Luxury planning", "Destination coordination", "VIP treatment"]}]');

-- Insert Venues
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('grand-palace-hotel', 'Grand Palace Hotel', 'Vikram Singh', 'Venues', '+91 98765 43213', '+91 98765 43213', 'vikram@grandpalace.com', 'Delhi, NCR', 'Elegant banquet halls with modern amenities and royal ambiance.', '10+ years', 4.7, 156, true, true, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400', '["Banquet Halls", "Garden Venues", "Rooftop Spaces"]', '["Hall Booking", "Catering", "Decoration"]', '[{"name": "Grand Hall", "price": "₹3,00,000", "features": ["500 guests", "AC hall", "Parking"]}]'),
('garden-paradise', 'Garden Paradise', 'Meera Reddy', 'Venues', '+91 98765 43214', '+91 98765 43214', 'meera@gardenparadise.com', 'Hyderabad, Telangana', 'Beautiful outdoor garden venues perfect for intimate weddings.', '5+ years', 4.5, 98, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Garden Venues", "Outdoor Events", "Intimate Weddings"]', '["Venue Booking", "Garden Setup", "Lighting"]', '[{"name": "Garden Package", "price": "₹1,50,000", "features": ["200 guests", "Garden setup", "Lighting"]}]'),
('skyline-terrace', 'Skyline Terrace', 'Arjun Mehta', 'Venues', '+91 98765 43215', '+91 98765 43215', 'arjun@skyline.com', 'Mumbai, Maharashtra', 'Rooftop venues with city skyline views for memorable celebrations.', '8+ years', 4.8, 134, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Rooftop Venues", "City Views", "Modern Spaces"]', '["Rooftop Booking", "View Setup", "Modern Amenities"]', '[{"name": "Skyline Package", "price": "₹2,50,000", "features": ["300 guests", "City views", "Modern setup"]}]');

-- Insert Photographers
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('royal-photography', 'Royal Photography Studio', 'Rajesh Kumar', 'Photographers', '+91 98765 43216', '+91 98765 43216', 'rajesh@royalphotography.com', 'Hyderabad, Telangana', 'Professional wedding photography with artistic vision and candid moments.', '8+ years', 4.9, 245, true, true, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', '["Wedding Photography", "Candid Shots", "Pre-wedding"]', '["Full Day Coverage", "Photo Editing", "Album Design"]', '[{"name": "Royal Package", "price": "₹75,000", "features": ["12 hours coverage", "500+ photos", "Album"]}]'),
('dream-captures', 'Dream Captures', 'Priya Sharma', 'Photographers', '+91 98765 43217', '+91 98765 43217', 'priya@dreamcaptures.com', 'Bangalore, Karnataka', 'Creative photography focusing on emotions and beautiful moments.', '6+ years', 4.7, 189, true, true, 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400', '["Emotional Photography", "Candid Moments", "Creative Shots"]', '["Full Day Coverage", "Emotional Shots", "Creative Editing"]', '[{"name": "Dream Package", "price": "₹65,000", "features": ["10 hours coverage", "400+ photos", "Creative editing"]}]'),
('pixel-perfect', 'Pixel Perfect Studios', 'Amit Kumar', 'Photographers', '+91 98765 43218', '+91 98765 43218', 'amit@pixelperfect.com', 'Delhi, NCR', 'Modern photography with drone shots and cinematic videos.', '4+ years', 4.6, 112, true, true, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', '["Drone Photography", "Cinematic Videos", "Modern Shots"]', '["Photography + Video", "Drone Shots", "Cinematic Editing"]', '[{"name": "Pixel Package", "price": "₹85,000", "features": ["Photography + Video", "Drone shots", "Cinematic editing"]}]');

-- Insert Decorators
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('royal-decorations', 'Royal Decorations', 'Sunita Gupta', 'Decorators', '+91 98765 43219', '+91 98765 43219', 'sunita@royaldecor.com', 'Mumbai, Maharashtra', 'Luxurious decorations with flowers and elegant themes.', '12+ years', 4.8, 278, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Flower Decorations", "Theme Design", "Stage Setup"]', '["Complete Decoration", "Flower Arrangements", "Theme Creation"]', '[{"name": "Royal Decor", "price": "₹1,20,000", "features": ["Complete decoration", "Fresh flowers", "Theme design"]}]'),
('bloom-creations', 'Bloom Creations', 'Ravi Patel', 'Decorators', '+91 98765 43220', '+91 98765 43220', 'ravi@bloomcreations.com', 'Ahmedabad, Gujarat', 'Creative floral decorations with unique designs.', '7+ years', 4.7, 156, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Floral Design", "Creative Arrangements", "Color Themes"]', '["Floral Decoration", "Creative Design", "Color Coordination"]', '[{"name": "Bloom Package", "price": "₹90,000", "features": ["Floral decoration", "Creative design", "Color themes"]}]'),
('elegant-events', 'Elegant Events Decor', 'Kavitha Reddy', 'Decorators', '+91 98765 43221', '+91 98765 43221', 'kavitha@elegantevents.com', 'Hyderabad, Telangana', 'Elegant and sophisticated decorations for special occasions.', '9+ years', 4.9, 203, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Elegant Themes", "Sophisticated Design", "Premium Decor"]', '["Elegant Decoration", "Premium Design", "Sophisticated Themes"]', '[{"name": "Elegant Package", "price": "₹1,50,000", "features": ["Elegant decoration", "Premium design", "Sophisticated themes"]}]');

-- Insert Caterers
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('spice-kitchen', 'Spice Kitchen', 'Chef Ramesh', 'Caterers', '+91 98765 43222', '+91 98765 43222', 'ramesh@spicekitchen.com', 'Chennai, Tamil Nadu', 'Authentic South Indian cuisine with traditional recipes.', '15+ years', 4.8, 312, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["South Indian Cuisine", "Traditional Recipes", "Veg & Non-veg"]', '["Complete Catering", "Traditional Food", "Live Counters"]', '[{"name": "Spice Package", "price": "₹800 per plate", "features": ["Traditional cuisine", "Live counters", "Desserts"]}]'),
('royal-taste', 'Royal Taste Caterers', 'Chef Priya', 'Caterers', '+91 98765 43223', '+91 98765 43223', 'priya@royaltaste.com', 'Delhi, NCR', 'Multi-cuisine catering with royal flavors and presentation.', '10+ years', 4.7, 245, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Multi-cuisine", "Royal Presentation", "North Indian"]', '["Multi-cuisine Catering", "Royal Presentation", "Live Cooking"]', '[{"name": "Royal Package", "price": "₹1,200 per plate", "features": ["Multi-cuisine", "Royal presentation", "Live cooking"]}]'),
('flavors-of-india', 'Flavors of India', 'Chef Amit', 'Caterers', '+91 98765 43224', '+91 98765 43224', 'amit@flavorsofindia.com', 'Mumbai, Maharashtra', 'Authentic Indian flavors with modern presentation.', '8+ years', 4.6, 189, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Indian Cuisine", "Modern Presentation", "Street Food"]', '["Indian Catering", "Modern Style", "Street Food Counters"]', '[{"name": "Flavors Package", "price": "₹1,000 per plate", "features": ["Indian cuisine", "Modern presentation", "Street food"]}]');

-- Insert Makeup Artists
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('glam-studio', 'Glam Studio', 'Meera Singh', 'Makeup Artists', '+91 98765 43225', '+91 98765 43225', 'meera@glamstudio.com', 'Mumbai, Maharashtra', 'Professional makeup artistry with glamorous looks.', '6+ years', 4.8, 167, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Bridal Makeup", "Glamorous Looks", "Photo Shoots"]', '["Bridal Makeup", "Hair Styling", "Photo Ready"]', '[{"name": "Glam Package", "price": "₹25,000", "features": ["Bridal makeup", "Hair styling", "Trial session"]}]'),
('beauty-bloom', 'Beauty Bloom', 'Kavitha Reddy', 'Makeup Artists', '+91 98765 43226', '+91 98765 43226', 'kavitha@beautybloom.com', 'Hyderabad, Telangana', 'Natural and elegant makeup for your special day.', '4+ years', 4.7, 134, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Natural Makeup", "Elegant Looks", "Bridal Packages"]', '["Natural Makeup", "Hair Styling", "Elegant Looks"]', '[{"name": "Bloom Package", "price": "₹20,000", "features": ["Natural makeup", "Hair styling", "Elegant look"]}]'),
('glamour-girls', 'Glamour Girls', 'Priya Sharma', 'Makeup Artists', '+91 98765 43227', '+91 98765 43227', 'priya@glamourgirls.com', 'Bangalore, Karnataka', 'Professional makeup with modern techniques and premium products.', '8+ years', 4.9, 201, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Professional Makeup", "Modern Techniques", "Premium Products"]', '["Professional Makeup", "Modern Techniques", "Premium Products"]', '[{"name": "Glamour Package", "price": "₹30,000", "features": ["Professional makeup", "Modern techniques", "Premium products"]}]');

-- Insert DJs, Lighting, and Entertainment
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('party-rockers', 'Party Rockers DJ', 'DJ Rahul', 'DJs, Lighting, and Entertainment', '+91 98765 43228', '+91 98765 43228', 'rahul@partyrockers.com', 'Mumbai, Maharashtra', 'High-energy DJ services with professional sound and lighting.', '5+ years', 4.7, 145, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Wedding DJ", "Sound System", "Lighting Effects"]', '["DJ Services", "Sound System", "Lighting"]', '[{"name": "Party Package", "price": "₹45,000", "features": ["DJ services", "Sound system", "Lighting effects"]}]'),
('music-masters', 'Music Masters', 'DJ Arjun', 'DJs, Lighting, and Entertainment', '+91 98765 43229', '+91 98765 43229', 'arjun@musicmasters.com', 'Delhi, NCR', 'Professional music and lighting for memorable celebrations.', '7+ years', 4.8, 178, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Music Mixing", "Lighting Design", "Sound Engineering"]', '["Music Mixing", "Lighting Design", "Sound Engineering"]', '[{"name": "Music Package", "price": "₹50,000", "features": ["Music mixing", "Lighting design", "Sound engineering"]}]'),
('beat-masters', 'Beat Masters Entertainment', 'DJ Priya', 'DJs, Lighting, and Entertainment', '+91 98765 43230', '+91 98765 43230', 'priya@beatmasters.com', 'Bangalore, Karnataka', 'Complete entertainment package with DJ, lighting, and special effects.', '6+ years', 4.6, 123, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Complete Entertainment", "Special Effects", "Dance Floor"]', '["DJ Services", "Special Effects", "Dance Floor"]', '[{"name": "Beat Package", "price": "₹55,000", "features": ["Complete entertainment", "Special effects", "Dance floor"]}]');

-- Insert Anchors
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('voice-of-celebrations', 'Voice of Celebrations', 'Rajesh Kumar', 'Anchors', '+91 98765 43231', '+91 98765 43231', 'rajesh@voiceofcelebrations.com', 'Hyderabad, Telangana', 'Professional anchoring with engaging personality and smooth flow.', '8+ years', 4.8, 156, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Wedding Anchoring", "Corporate Events", "Engaging Personality"]', '["Event Anchoring", "Script Writing", "Audience Engagement"]', '[{"name": "Voice Package", "price": "₹35,000", "features": ["Event anchoring", "Script writing", "Audience engagement"]}]'),
('star-anchors', 'Star Anchors', 'Priya Sharma', 'Anchors', '+91 98765 43232', '+91 98765 43232', 'priya@staranchors.com', 'Mumbai, Maharashtra', 'Charming and professional anchoring for special occasions.', '5+ years', 4.7, 134, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Charming Personality", "Professional Anchoring", "Special Occasions"]', '["Professional Anchoring", "Charming Personality", "Special Occasions"]', '[{"name": "Star Package", "price": "₹30,000", "features": ["Professional anchoring", "Charming personality", "Special occasions"]}]'),
('perfect-hosts', 'Perfect Hosts', 'Amit Patel', 'Anchors', '+91 98765 43233', '+91 98765 43233', 'amit@perfecthosts.com', 'Delhi, NCR', 'Perfect hosting with humor and elegance for memorable events.', '6+ years', 4.6, 112, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Humor & Elegance", "Perfect Hosting", "Memorable Events"]', '["Perfect Hosting", "Humor & Elegance", "Memorable Events"]', '[{"name": "Perfect Package", "price": "₹32,000", "features": ["Perfect hosting", "Humor & elegance", "Memorable events"]}]');

-- Insert Transportation Services
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('royal-rides', 'Royal Rides', 'Vikram Singh', 'Transportation Services', '+91 98765 43234', '+91 98765 43234', 'vikram@royalrides.com', 'Delhi, NCR', 'Luxury car rentals for weddings and special occasions.', '10+ years', 4.8, 189, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Luxury Cars", "Wedding Cars", "Special Occasions"]', '["Luxury Car Rental", "Wedding Cars", "Special Occasions"]', '[{"name": "Royal Package", "price": "₹25,000 per day", "features": ["Luxury cars", "Wedding decoration", "Professional driver"]}]'),
('dream-wheels', 'Dream Wheels', 'Meera Reddy', 'Transportation Services', '+91 98765 43235', '+91 98765 43235', 'meera@dreamwheels.com', 'Hyderabad, Telangana', 'Premium car rentals with professional drivers.', '7+ years', 4.7, 145, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Premium Cars", "Professional Drivers", "Wedding Transport"]', '["Premium Car Rental", "Professional Drivers", "Wedding Transport"]', '[{"name": "Dream Package", "price": "₹20,000 per day", "features": ["Premium cars", "Professional drivers", "Wedding transport"]}]'),
('elite-transport', 'Elite Transport', 'Arjun Mehta', 'Transportation Services', '+91 98765 43236', '+91 98765 43236', 'arjun@elitetransport.com', 'Mumbai, Maharashtra', 'Elite transportation services for luxury events.', '8+ years', 4.9, 167, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Elite Transport", "Luxury Events", "Fleet Management"]', '["Elite Transport", "Luxury Events", "Fleet Management"]', '[{"name": "Elite Package", "price": "₹30,000 per day", "features": ["Elite transport", "Luxury events", "Fleet management"]}]');

-- Insert Fashion/Costume Designers
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('royal-boutique', 'Royal Boutique', 'Sunita Gupta', 'Fashion/Costume Designers', '+91 98765 43237', '+91 98765 43237', 'sunita@royalboutique.com', 'Mumbai, Maharashtra', 'Exclusive designer wear for brides and grooms.', '12+ years', 4.9, 234, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Bridal Wear", "Groom Wear", "Designer Outfits"]', '["Bridal Wear", "Groom Wear", "Designer Outfits"]', '[{"name": "Royal Package", "price": "₹1,00,000", "features": ["Bridal wear", "Groom wear", "Designer outfits"]}]'),
('style-studio', 'Style Studio', 'Ravi Patel', 'Fashion/Costume Designers', '+91 98765 43238', '+91 98765 43238', 'ravi@stylestudio.com', 'Ahmedabad, Gujarat', 'Contemporary fashion with traditional touch.', '8+ years', 4.7, 178, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Contemporary Fashion", "Traditional Touch", "Custom Design"]', '["Contemporary Fashion", "Traditional Touch", "Custom Design"]', '[{"name": "Style Package", "price": "₹75,000", "features": ["Contemporary fashion", "Traditional touch", "Custom design"]}]'),
('elegant-ensembles', 'Elegant Ensembles', 'Kavitha Reddy', 'Fashion/Costume Designers', '+91 98765 43239', '+91 98765 43239', 'kavitha@elegantensembles.com', 'Hyderabad, Telangana', 'Elegant and sophisticated fashion designs.', '6+ years', 4.8, 156, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Elegant Designs", "Sophisticated Fashion", "Custom Tailoring"]', '["Elegant Designs", "Sophisticated Fashion", "Custom Tailoring"]', '[{"name": "Elegant Package", "price": "₹85,000", "features": ["Elegant designs", "Sophisticated fashion", "Custom tailoring"]}]');

-- Insert Tent & Equipment Rentals
INSERT INTO vendors (slug, brand_name, spoc_name, category, phone_number, whatsapp_number, email, address, description, experience, rating, review_count, verified, currently_available, avatar_url, specialties, services, packages) VALUES
('royal-tents', 'Royal Tents & Equipment', 'Vikram Singh', 'Tent & Equipment Rentals', '+91 98765 43240', '+91 98765 43240', 'vikram@royaltents.com', 'Delhi, NCR', 'Premium tents and equipment for outdoor events.', '15+ years', 4.8, 267, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Premium Tents", "Outdoor Equipment", "Event Setup"]', '["Tent Rental", "Equipment Rental", "Event Setup"]', '[{"name": "Royal Package", "price": "₹2,00,000", "features": ["Premium tents", "Outdoor equipment", "Event setup"]}]'),
('tent-masters', 'Tent Masters', 'Meera Reddy', 'Tent & Equipment Rentals', '+91 98765 43241', '+91 98765 43241', 'meera@tentmasters.com', 'Hyderabad, Telangana', 'Complete tent and equipment solutions for events.', '10+ years', 4.7, 189, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Complete Solutions", "Tent Setup", "Equipment Rental"]', '["Complete Solutions", "Tent Setup", "Equipment Rental"]', '[{"name": "Masters Package", "price": "₹1,50,000", "features": ["Complete solutions", "Tent setup", "Equipment rental"]}]'),
('event-equipment', 'Event Equipment Hub', 'Arjun Mehta', 'Tent & Equipment Rentals', '+91 98765 43242', '+91 98765 43242', 'arjun@eventequipment.com', 'Mumbai, Maharashtra', 'Modern equipment and tent solutions for events.', '8+ years', 4.6, 145, true, true, 'https://images.unsplash.com/photo-1519167758481-83f1426b0e4e?w=400', '["Modern Equipment", "Tent Solutions", "Event Setup"]', '["Modern Equipment", "Tent Solutions", "Event Setup"]', '[{"name": "Hub Package", "price": "₹1,80,000", "features": ["Modern equipment", "Tent solutions", "Event setup"]}]');

-- Re-enable RLS after insertion
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_media ENABLE ROW LEVEL SECURITY;

-- Verify the data
SELECT category, COUNT(*) as vendor_count FROM vendors GROUP BY category ORDER BY category;
